# Generated by Django 4.0.10 on 2023-02-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('NamaLengkap', models.CharField(max_length=500)),
                ('EmailPengguna', models.TextField(primary_key=True, serialize=False)),
                ('NoTelp', models.TextField()),
            ],
        ),
    ]
